
[package]
name = "rune-remote"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
axum = { version = "0.7", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.5"
walkdir = "2.4"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
hyper = "1.0"

[dev-dependencies]
tempfile = "3.8"
